services:
  central:
    build:
      context: .
      dockerfile: Dockerfile.central
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/meetings
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      REDIS_HOST: redis

  employee:
    build:
      context: .
      dockerfile: Dockerfile.employee
    depends_on:
      - central
    environment:
      CENTRAL_WS_URL: ws://central:8080/ws

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: meetings
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--save", "60", "1"]

volumes:
  db_data:
