services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: meetings
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--save", "60", "1"]

  backend:
    build: ../meeting-manager/backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/meetings
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: