services:
  central:
    build: aaaa
    image: benjamin6942/meeting-manager-central:latest
    ports:
      - "8080:8080"
  employee1:
    build: meeting-manager-employee
    image: benjamin6942/meeting-manager-employee:emp1
    environment:
      EMPLOYEE_NAME: emp1
    depends_on:
      - central
  employee2:
    build: meeting-manager-employee
    image: benjamin6942/meeting-manager-employee:emp2
    environment:
      EMPLOYEE_NAME: emp2
    depends_on:
      - central
  # repetir employee3,4,5...
volumes:
  data:
    driver: local